app = 'broadcasting-news-aggregator'
primary_region = 'sjc'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20
  
  [[http_service.checks]]
    grace_period = "300s"
    interval = "60s"
    method = "GET"
    timeout = "15s"
    path = "/healthz"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
